
services:
  postgres-service:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=shareit-alena
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  payment-service:
    build: payment-service/.
    ports:
      - "8080:8080"
    depends_on:
      - postgres-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_HOST=postgres-service
      - DB_NAME=shareit-alena
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  order-service:
    build: order-service/.
    ports:
      - "8081:8081"
    depends_on:
      - postgres-service
      - payment-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_HOST=postgres-service
      - DB_NAME=shareit-alena
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
